name: Mac Test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Depoyu klonla (Checkout)
        uses: actions/checkout@v4

      - name: DMG dosyasını aç (Mount)
        run: hdiutil attach app.dmg

      - name: Uygulamayı Çalıştır (Test)
        run: |
          echo "Uygulama dosyaları kontrol ediliyor..."
          ls -la "/Volumes/OA Trade - Delta0x/main.app/Contents/MacOS/"
          
          echo "-----------------------------------"
          echo "Uygulama başlatılıyor..."
          # Asıl çalıştırılabilir dosyayı tetikliyoruz
          "/Volumes/OA Trade - Delta0x/main.app/Contents/MacOS/main"
