name: Mac Test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Depoyu klonla (Checkout)
        uses: actions/checkout@v4

      - name: DMG dosyasını aç (Mount)
        run: hdiutil attach app.dmg

      - name: DMG Klasörünün İçine Bak
        run: ls -la "/Volumes/OA Trade - Delta0x/"
